### ISSUE TITLE
[BUG] TIG street is required when switching to different country

### ISSUE THREAD

**Issue by Paulsky** [postcodeservice/postcode-magento2#51] opened 2022-11-24 10:37 UTC
**To Reproduce**
1. Enable another country next to BE and NL. For example Germany
2. Go to checkout
3. Select Germany

**Expected result**
TIG Street is hidden and not required

**Actual result**
TIG Street is shown and required. Now there are two street fields

**Workaround**
None, I'm wrting some JS for fixing this bug and other TIG bugs

- Magento version: [Magento 2.4.5]
- PHP version: [8.1]

**Comment by Paulsky** [comment] 2022-11-24 13:04
@tig-jeffreybranderhorst,

Thank you for your reply. Yes, this is happening with OSC enabled. I'm referring to the other bugs (https://github.com/tig-nl/postcode-magento2/issues/52, https://github.com/tig-nl/postcode-magento2/issues/53, https://github.com/tig-nl/postcode-magento2/issues/46)

**Comment by tig-jeffreybranderhorst** [comment] 2022-11-24 13:07
Hi @Paulsky ,

Which OSC is this? And which version of the extension?  I have also replied on your other github issues. I see #46 should be fixed in the newest version of the extension. 

Have a great day,
Jeffrey

**Comment by Paulsky** [comment] 2022-11-24 13:14
@tig-jeffreybranderhorst this is https://knowledgebase.onestepcheckout.com/magento-2/getting-started-with-m2/changelogs/ ver_1.2.059

**Comment by tig-jeffreybranderhorst** [comment] 2022-11-24 13:28
Hi @Paulsky ,

Thank you for the update, we do not have support on the OSC of onestepcheckout.com at this moment. In the future it is possible we are compatible with the OSC from onestepcheckout.com, but at this moment the extension is not yet compatible.  Because I was not able to reproduce the issue on default checkout, I suspect the issue is caused by a conflict between the OSC and the postcode checker. 


Have a great day,
Jeffrey

**Comment by schldwcht** [comment] 2023-05-02 10:58
Hi @Paulsky,
I wanted to inform you that, after careful consideration, we have decided not to support the OSC of OneStepCheckout.com at this time. Although we may revisit this decision in the future, we have decided to close this issue for the time being.
Best regards,
Joost

**Closed by schldwcht** 2023-05-02 10:58 UTC
